src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'paniers')]
    private $utilisateur;

    #[ORM\Column(type: 'date')]
    private $date_achat;

    #[ORM\Column(type: 'boolean')]
    private $etat;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: ContenuPanier::class)]
    private $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, ContenuPanier>
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): self
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers[] = $contenuPanier;
            $contenuPanier->setPanier($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): self
    {
        if ($this->contenuPaniers->removeElement($contenuPanier)) {
            // set the owning side to null (unless already changed)
            if ($contenuPanier->getPanier() === $this) {
                $contenuPanier->setPanier(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }
}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_achat')
            ->add('etat')
            ->add('utilisateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/panier')]
class PanierController extends AbstractController
{
    #[Route('/', name: 'panier_index', methods: ['GET', 'POST'])]
    public function index(PanierRepository $panierRepository, EntityManagerInterface $entityManager): Response
    {
        $user=$this->getUser();
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findAll(),
            'user'=>$user,
        ]);
        
    }

    #[Route('/new', name: 'panier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
       
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);
       

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($panier);
            $entityManager->flush();

            return $this->redirectToRoute('panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'panier_show', methods: ['GET'])]
    public function show(Panier $panier,EntityManagerInterface $entityManager): Response
    {

        $panier->setEtat('1');     
        $entityManager->persist($panier);
        $entityManager->flush();
        $this->addFlash('success', 'article valider!');

         return $this->redirectToRoute('panier_index', [], Response::HTTP_SEE_OTHER);
        
    }

    #[Route('/{id}/edit', name: 'panier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Panier $panier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'panier_delete', methods: ['POST'])]
    public function delete(Request $request, Panier $panier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $entityManager->remove($panier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('panier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('panier_index') }}">back to list</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}


    <h1> mon profile </h1>
      <table class="table">
       <thead>
    <tr>
                <th>Id</th>
                <th>nom</th>
                <th>prenom</th>
               
    </tr>
    </thead>
    <tbody>
     <tr>
                <th>{{ user.id }}</th>
                <th>{{ user.nom }}</th>
                <th>{{ user.prenom }}</th>
               
    </tr>
    </tbody>
     </table>
  
    <h1>mes commandes </h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_achat</th>
                <th>Etat</th>
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
                <td>{{ panier.id }}</td>
                <td>{{ panier.dateAchat ? panier.dateAchat|date('Y-m-d') : '' }}</td>
                <td>{{ panier.etat ? 'Yes' : 'No' }}</td>
              
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('produit_index') }}">retour au produit</a>
{% endblock %}

templates/panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
    <h1>Create new Panier</h1>

    {{ include('panier/_form.html.twig') }}

    <a href="{{ path('panier_index') }}">back to list</a>
{% endblock %}

templates/panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>Date_achat</th>
                <td>{{ panier.dateAchat ? panier.dateAchat|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ panier.etat ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('panier_index') }}">back to list</a>

    <a href="{{ path('panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}